#%RAML 1.0 DataType
description: Represents an Employee
properties:
  id?:
    type: number
  birth_date:
    type: date-only
  first_name:
    type: string
  last_name:
    type: string
  gender:
    enum: [F,M]
  hire_date:
    type: date-only
  titles:
    type: array
    items: 
      type: !include employee-title.raml
  departments:
    type: array
    items:
      type: !include employee-department.raml
  salaries:
    type: array
    items: 
      type: !include employee-salary.raml

examples:
  !include ../../examples/employee-operations/get/employee-item.raml