#%RAML 1.0 DataType
properties:
  title:
    enum: [Senior Engineer, Staff, Engineer, Senior Staff, Assistant Engineer, Technique Leader, Manager]
  from:
    type: date-only
  to?: 
    type: date-only