#%RAML 1.0 Library
usage: contains the data type definitions for emplooyee based operations

types:
  Employee: !include data-types/employees/employee.raml
  Titles: !include data-types/titles/title-list.raml
  GetDepartments: !include data-types/departments/department-collection.raml
  GetDepartment: !include data-types/departments/department.raml
  PostDepartment: !include data-types/departments/base-deparment.raml