#%RAML 1.0 DataType
description: Describes that an asyncronous process was accepted to be executed
properties:
  title:
    type: string
  message:
    type: string
  
examples:
  !include ../examples/process-accepted.raml